call code --install-extension vscodevim.vim
call code --install-extension MS-CEINTL.vscode-language-pack-ja
call code --install-extension rust-lang.rust-analyzer
call code --install-extension vadimcn.vscode-lldb
call code --install-extension bungcip.better-toml
call code --install-extension ritwickdey.liveserver
call code --install-extension golang.go
call code --install-extension premparihar.gotestexplorer
call code --install-extension bierner.markdown-preview-github-styles
call code --install-extension humao.rest-client
call code --install-extension nonylene.dark-molokai-theme